### ISSUE TITLE
Not working with 7.9.2

### ISSUE THREAD

**Issue by robetus** [Lyphiard/WHMCS-PayPalBillingAgreements#1]
A lot of errors in WHMCS 7.9.2. Are you planning on maintaining WHMCS upgrades?

**Comment by jamesw343** [comment]
Can you please post the errors you're getting? This should work fine with 7.9.2.

**Comment by robetus** [comment]
Really sorry about this, I didn't follow the directions fully. This module is great! Seems to be solidly coded. I really hope you're planning on updating regularly. Thank you for your work.
